services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    env_file:
      - path: .env
        required: false
      - path: stack.env
        required: false
    restart: unless-stopped
