[project]
name = "discord-voice-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "edge-tts>=7.0.2",
    "miniaudio>=1.61",
    "py-cord[voice]>=2.6.1",
    "python-dotenv>=1.1.0",
]
